[general]
import = [
  "~/.config/alacritty/themes/alacritty-theme/themes/gruvbox_material_hard_dark.toml.toml"
]

[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
#bold.family = "JetBrains Mono Nerd Font"
#italic.family = "JetBrains Mono Nerd Font"
#bold_italic.family = "JetBrains Mono Nerd Font"
size = 14.0

